name: Deploy

on:
  push:
    tags:
      - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Skip for non-tagged refs
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "Dispatched from ${{github.ref}} — skipping deploy"
          exit 1

      - name: Checkout ui/edu.ai branch
        uses: actions/checkout@v4
        with:
          ref: ui/edu.ai

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set basePath variable
        id: vars
        run: echo "basePath=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Build
        run: npm run build:prod -- --base=/${{ env.basePath }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4